### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by juev** [piranha/beartest#1]
Привет,

пробуешь использовать bear? Купил подписку? А для чего планируешь использовать?

В файле пароль сборосил? ;) 

Несекурно.

**Comment by sansolovyov** [comment]
:-) https://www.youtube.com/watch?v=5ll2JM-Rj2o

**Comment by sansolovyov** [comment]
Блин, спасибо за вопрос про пароль, понял теперь, в чём проблема была ))

**Comment by juev** [comment]
Спасибо, посмотрю!
